apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    release: {{ .Release.Name }}
    project: counter
spec:
  serviceName: redis
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      project: counter
      app: redis
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        project: counter
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            requests:
              cpu: 30m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - name: redis
              containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    release: {{ .Release.Name }}
    project: counter
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    release: {{ .Release.Name }}
    project: counter
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-counter
  labels:
    release: {{ .Release.Name }}
    project: counter
spec:
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      project: counter
      app: counter
  replicas: 2
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        project: counter
        app: counter
    spec:
      containers:
        - name: counter
          image: ondrejsika/counter
          resources:
            requests:
              cpu: 20m
              memory: 20Mi
            limits:
              cpu: 200m
              memory: 100Mi
          env:
            - name: REDIS
              value: {{ .Release.Name }}-redis
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-counter
  labels:
    release: {{ .Release.Name }}
    project: counter
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    release: {{ .Release.Name }}
    project: counter
    app: counter
