apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  rules:
    - host: {{ required "host is required" .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ .Release.Name }}-counter
              servicePort: 80
